MyNUnitWeb/MyNUnitWeb/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyNUnitWeb.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        this.logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

MyNUnitWeb/MyNUnitWeb/Pages/Index.cshtml.cs
namespace MyNUnitWeb.Pages;

using Data;
using Microsoft.EntityFrameworkCore;
using MyNUnit.Info;

public class IndexModel : PageModel
{ 
    private readonly TestInfoDbContext infoContext;

    private readonly IWebHostEnvironment environment;
    
    public IndexModel(IWebHostEnvironment environment, TestInfoDbContext infoContext)
    {
        this.environment = environment;
        this.infoContext = infoContext;
    }

    public IList<TestInfo> TestInfos { get; private set; } = new List<TestInfo>();

    public async Task OnGetAsync()
    {
        TestInfos = await infoContext.TestsInfo
            .Include(testsInfo => testsInfo.AssembliesTestInfo)
            .ThenInclude(assemblyInfo => assemblyInfo.ClassesInfo)
            .ThenInclude(classInfo => classInfo.MethodsInfo)
            .OrderByDescending(info => info.TestInfoId).ToListAsync();
    }
    
    public async Task<IActionResult> OnPostUploadAsync(List<IFormFile> files)
    {
        string wwwPath = environment.WebRootPath;

        await CreateFiles(files, wwwPath);

        return RedirectToPage("./Index");
    }

    public async Task<IActionResult> OnPostRunTests()
    {
        string wwwPath = environment.WebRootPath;

        var filesPath = Path.Combine(wwwPath, "Uploads");
        var assembliesList = MyNUnit.MyNUnit.StartAllTests(filesPath);

        var dbList = assembliesList.Select(assemblyTestInfo => new AssemblyTestInfoDb
            {
                Name = assemblyTestInfo.Name.Name,
                ClassesInfo = GetClassesInfo(assemblyTestInfo)
            })
            .ToList();

        if (dbList.Count != 0)
        {
            var info = new TestInfo
            {
                AssembliesTestInfo = dbList,
                TestDate = DateTime.Now,
            };
            
            infoContext.TestsInfo.Add(info);
            await infoContext.SaveChangesAsync();
        }

        DeleteFiles(filesPath);

        return RedirectToPage("./Index");
    }

    private static async Task CreateFiles(List<IFormFile> files, string path)
    {
        foreach (var file in files)
        {
            if (file.Length <= 0)
            {
                continue;
            }
            
            var filePath = Path.Combine(path, "Uploads");

            if (!Directory.Exists(filePath))
            {
                Directory.CreateDirectory(filePath);
            }

            await using var stream = System.IO.File.Create(Path.Combine(filePath, Path.GetRandomFileName()));
            await file.CopyToAsync(stream);
        }
    }
    
    private static void DeleteFiles(string path)
    {
        var files = Directory.GetFiles(path);
        foreach (var fileName in files)
        {
            System.IO.File.Delete(fileName);
        }
    }

    private static List<ClassTestInfoDb> GetClassesInfo(AssemblyTestInfo info)
        => info.ClassesInfo.Select(classInfo => new ClassTestInfoDb
            {
                Name = classInfo.Name,
                MethodsInfo = GetMethodsInfo(classInfo), State = classInfo.State
            })
            .ToList();

    private static List<MethodTestInfoDb>? GetMethodsInfo(ClassTestInfo classInfo)
        => classInfo.MethodsInfo?.Select(methodInfo => new MethodTestInfoDb
            {
                Name = methodInfo.Name,
                State = methodInfo.State,
                CompletionTime = methodInfo.CompletionTime,
                Ignored = methodInfo.Ignored,
                HasCaughtException = methodInfo.HasCaughtException,
                ExpectedExceptionType = methodInfo.ExceptionInfo?.ExpectedExceptionType?.ToString(),
                ActualExceptionType = methodInfo.ExceptionInfo?.ActualException?.GetType().ToString(),
            })
            .ToList();
}

MyNUnitWeb/MyNUnitWeb/Pages/Index.cshtml
@page
@using MyNUnit.State
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h5>Upload MyNUnit test projects and get test results.</h5>
</div>

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <dl>
            <dd>
                <input type="file" name="files" class="form-control" multiple/>
            </dd>
            <input asp-page-handler="Upload" class="btn btn-success" type="submit" value="Upload!"/>
        </dl>
    </form>
</div>

<div class="align-content-center">
    <form method="post">
        <input asp-page-handler="RunTests" class="btn btn-primary btn-lg" type="submit" value="Run tests">
    </form>
</div>

<table class="table">
    <thead>
    <tr>
        <th scope="col">Assembly name</th>
        <th scope="col">Amount of successful tests</th>
        <th scope="col">Amount of unsuccessful tests</th>
        <th scope="col">Date</th>
    </tr>
    </thead>
    
    <tbody>
    @foreach (var info in Model.TestInfos)
    {
        @foreach (var assemblyInfo in info.AssembliesTestInfo)
        {
            <tr data-bs-toggle="collapse" data-bs-target="#methods_@assemblyInfo.AssemblyTestInfoDbId">
                <td>
                    <button class="btn btn-outline-dark" type="button">
                        @assemblyInfo.Name
                    </button>
                </td>
                <td>@assemblyInfo.GetSuccessfulTestsCount()</td>
                <td>@assemblyInfo.GetUnsuccessfulTestsCount()</td>
                <td>@info.TestDate</td>
            </tr>
            
            <tr class="collapse" id="methods_@assemblyInfo.AssemblyTestInfoDbId">
                <td colspan="6">
                    <div class="collapse" id="methods_@assemblyInfo.AssemblyTestInfoDbId">
                        <table class="table">
                            <tr>
                                <th>Class name</th>
                                <th>Status</th>
                            </tr>
                            
                            @foreach (var classInfo in assemblyInfo.ClassesInfo)
                            {
                                string color = classInfo.State == ClassState.Passed
                                    ? "table-success"
                                    : "table-warning";

                                <tr class="@color">
                                    <td>@classInfo.Name</td>
                                    <td>@classInfo.State</td>
                                </tr>
                            }
                        </table>
                    </div>
                    
                    <div class="collapse" id="methods_@assemblyInfo.AssemblyTestInfoDbId">
                        <table class="table">
                            <tr>
                                <th>Method name</th>
                                <th>Status</th>
                                <th>Ignore message</th>
                                <th>Completion time</th>
                                <th>Thrown exception</th>
                                <th>Expected exception</th>
                            </tr>

                            @foreach (var methodInfo in assemblyInfo.ClassesInfo.SelectMany(classInfo => classInfo.MethodsInfo))
                            {
                                string color;
                                if (methodInfo.State == TestState.Passed)
                                {
                                    color = "table-success";
                                }
                                else if (methodInfo.State == TestState.Ignored)
                                {
                                    color = "table-warning";
                                }
                                else
                                {
                                    color = "table-danger";
                                }
                                
                                <tr class="@color">
                                    <td>@methodInfo.Name</td>
                                    <td>@methodInfo.State</td>
                                    <td>@methodInfo.Ignored</td>
                                    <td>@methodInfo.CompletionTime</td>
                                    <td>@methodInfo.ActualExceptionType</td>
                                    <td>@methodInfo.ExpectedExceptionType</td>
                                </tr>
                            }
                        </table>
                    </div>
                </td> 
            </tr>
        }
    }
    </tbody>
</table>

MyNUnitWeb/MyNUnitWeb/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MyNUnitWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MyNUnitWeb.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">MyNUnitWeb</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - Piletskii-Oleg
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>